# Generated by Django 3.0.7 on 2020-08-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
    ]
