# Generated by Django 3.0.7 on 2020-07-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0002_auto_20200710_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('phonenumber', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=350)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='prayerrequest',
            options={'ordering': ['-date']},
        ),
    ]
