# Generated by Django 3.0.7 on 2020-07-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0004_auto_20200717_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertname', models.CharField(max_length=200)),
                ('photo', models.FileField(blank=True, null=True, upload_to='images/')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['active'],
            },
        ),
    ]
