# Generated by Django 3.0.7 on 2020-07-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0005_advert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phonenumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
