# Generated by Django 3.0.7 on 2020-07-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0006_auto_20200717_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.FileField(blank=True, null=True, upload_to='images/')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='phonenumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
