# Generated by Django 3.0.7 on 2020-07-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0007_auto_20200717_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
