# Generated by Django 3.0.7 on 2020-07-18 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0008_auto_20200718_0558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-id']},
        ),
    ]
