# Generated by Django 3.0.7 on 2020-07-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0009_auto_20200718_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
