# Generated by Django 3.0.7 on 2020-07-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0011_auto_20200718_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic'),
        ),
    ]
