# Generated by Django 3.0.7 on 2020-07-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0012_auto_20200723_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, unique=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('vlink', models.URLField(blank=True, null=True)),
                ('info', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('summary', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Ministries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, unique=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('vlink', models.URLField(blank=True, null=True)),
                ('info', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('summary', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
