# Generated by Django 3.0.7 on 2020-07-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0013_event_ministries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ministries',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='publication',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
