# Generated by Django 3.0.7 on 2020-08-30 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0014_auto_20200726_0932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ministries',
            new_name='Ministry',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='ministry',
            options={'verbose_name_plural': 'Ministries'},
        ),
    ]
